
cd "E:\M3 SE\EmoF\EmoF"
start cmd /C "nodemon app.js"
cd "E:\M3 SE\EmoF\EmoF\server\services\loginService"
start cmd /C "nodemon loginServer.js"
cd "E:\M3 SE\EmoF\EmoF\server\services\productsService"
start cmd /C "nodemon productsServer.js"
cd "E:\M3 SE\EmoF\EmoF\server\services\registerService"
start cmd /C "nodemon registerServer.js"
cd "E:\M3 SE\EmoF\EmoF\server\services\reviewService"
start cmd /C "nodemon reviewServer.js"
cd "E:\M3 SE\EmoF\EmoF\server\services\userInfoService"
start cmd /C "nodemon userInfoServer.js"
