
cd "EmoF"
start cmd /C "nodemon app.js"
cd "server\services\loginService"
start cmd /C "nodemon loginServer.js"
cd "..\productsService"
start cmd /C "nodemon productsServer.js"
cd "..\registerService"
start cmd /C "nodemon registerServer.js"
cd "..\reviewService"
start cmd /C "nodemon reviewServer.js"
cd "..\userInfoService"
start cmd /C "nodemon userInfoServer.js"
cd "..\statisticsService"
start cmd /C "nodemon statisticsServer.js"