
cd "C:\Users\Miruna\Documents\GitHub\EmoF"
start cmd /C "nodemon app.js"
cd "C:\Users\Miruna\Documents\GitHub\EmoF\server\services\loginService"
start cmd /C "nodemon loginServer.js"
cd "C:\Users\Miruna\Documents\GitHub\EmoF\server\services\productsService"
start cmd /C "nodemon productsServer.js"
cd "C:\Users\Miruna\Documents\GitHub\EmoF\server\services\registerService"
start cmd /C "nodemon registerServer.js"
cd "C:\Users\Miruna\Documents\GitHub\EmoF\server\services\reviewService"
start cmd /C "nodemon reviewServer.js"
cd "C:\Users\Miruna\Documents\GitHub\EmoF\server\services\userInfoService"
start cmd /C "nodemon userInfoServer.js"